"""followers

Revision ID: 519e0be4912a
Revises: 2fb0ed054530
Create Date: 2021-08-23 20:54:33.567322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519e0be4912a'
down_revision = '2fb0ed054530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
